import type { Product } from "./products.interface";


export const productsMock: Product[] = [
  { id: 1, title: "Wireless Headphones", price: 79.99, category: "Electronics" },
  { id: 2, title: "Leather Wallet", price: 34.5, category: "Accessories" },
  { id: 3, title: "Running Shoes", price: 120.0, category: "Footwear" },
  { id: 4, title: "Bluetooth Speaker", price: 49.99, category: "Electronics" },
  { id: 5, title: "Cotton T-Shirt", price: 19.99, category: "Clothing" },
  { id: 6, title: "Yoga Mat", price: 29.99, category: "Fitness" },
  { id: 7, title: "Stainless Water Bottle", price: 24.99, category: "Accessories" },
  { id: 8, title: "Smartwatch", price: 199.99, category: "Electronics" },
  { id: 9, title: "Denim Jacket", price: 89.99, category: "Clothing" },
  { id: 10, title: "Trail Boots", price: 150.0, category: "Footwear" },
  { id: 11, title: "Noise-Cancelling Earbuds", price: 129.99, category: "Electronics" },
  { id: 12, title: "Canvas Backpack", price: 59.99, category: "Accessories" },
  { id: 13, title: "Resistance Bands Set", price: 18.99, category: "Fitness" },
  { id: 14, title: "Wool Sweater", price: 64.99, category: "Clothing" },
  { id: 15, title: "Slip-On Sneakers", price: 55.0, category: "Footwear" },
  { id: 16, title: "Portable Charger", price: 39.99, category: "Electronics" },
  { id: 17, title: "Sunglasses", price: 27.5, category: "Accessories" },
  { id: 18, title: "Dumbbells 10kg Pair", price: 45.0, category: "Fitness" },
  { id: 19, title: "Linen Shorts", price: 34.99, category: "Clothing" },
  { id: 20, title: "Hiking Sandals", price: 68.0, category: "Footwear" },
  { id: 21, title: "USB-C Hub", price: 32.99, category: "Electronics" },
  { id: 22, title: "Leather Belt", price: 22.0, category: "Accessories" },
  { id: 23, title: "Jump Rope", price: 12.99, category: "Fitness" },
  { id: 24, title: "Graphic Hoodie", price: 49.99, category: "Clothing" },
  { id: 25, title: "Platform Boots", price: 110.0, category: "Footwear" },
  { id: 26, title: "Mechanical Keyboard", price: 89.99, category: "Electronics" },
  { id: 27, title: "Crossbody Bag", price: 42.0, category: "Accessories" },
  { id: 28, title: "Foam Roller", price: 21.99, category: "Fitness" },
  { id: 29, title: "Chino Pants", price: 54.99, category: "Clothing" },
  { id: 30, title: "Canvas Loafers", price: 47.0, category: "Footwear" },
  { id: 31, title: "Webcam HD", price: 59.99, category: "Electronics" },
  { id: 32, title: "Travel Organizer", price: 16.99, category: "Accessories" },
  { id: 33, title: "Kettlebell 12kg", price: 38.0, category: "Fitness" },
  { id: 34, title: "Polo Shirt", price: 29.99, category: "Clothing" },
  { id: 35, title: "Leather Oxfords", price: 135.0, category: "Footwear" },
];
